const PROPERTIES = [
  {
    id: "PROP-001",
    name: "The Layar Villa",
    location: "Seminyak, Bali",
    type: "Villa",
    emoji: "🏖️",
    totalValueUSD: 850000,
    tokenPriceUSD: 50,
    totalTokens: 17000,
    soldTokens: 13260,
    annualYield: 9.2,
    status: "Active",
    tags: ["Rental Income", "Bali"],
    description: "Luxury 4-bedroom villa in the heart of Seminyak with private pool, 200m from the beach. Fully managed by a professional hospitality operator with 92% average occupancy.",
    images: ["🏖️"],
    details: {
      bedrooms: 4,
      bathrooms: 4,
      landSize: "600 sqm",
      buildingSize: "420 sqm",
      yearBuilt: 2021,
      occupancyRate: "92%",
      managedBy: "Bali Luxury Stays",
    },
    tokenAddress: "0x1234...abcd",
    network: "BNB Chain",
  },
  {
    id: "PROP-002",
    name: "Sudirman Tower Suite",
    location: "Jakarta Selatan",
    type: "Apartment",
    emoji: "🏙️",
    totalValueUSD: 320000,
    tokenPriceUSD: 25,
    totalTokens: 12800,
    soldTokens: 5120,
    annualYield: 7.4,
    status: "Active",
    tags: ["Rental Income", "Jakarta"],
    description: "Premium 2-bedroom apartment on the 28th floor of Sudirman Tower with panoramic city views. Located in Jakarta's central business district, steps from MRT.",
    images: ["🏙️"],
    details: {
      bedrooms: 2,
      bathrooms: 2,
      landSize: "—",
      buildingSize: "85 sqm",
      yearBuilt: 2019,
      occupancyRate: "88%",
      managedBy: "Urban Living Jakarta",
    },
    tokenAddress: "0x5678...efgh",
    network: "BNB Chain",
  },
  {
    id: "PROP-003",
    name: "Ubud Jungle Retreat",
    location: "Ubud, Bali",
    type: "Villa",
    emoji: "🌿",
    totalValueUSD: 540000,
    tokenPriceUSD: 30,
    totalTokens: 18000,
    soldTokens: 18000,
    annualYield: 10.1,
    status: "Sold Out",
    tags: ["Sold Out", "Bali"],
    description: "Eco-luxury 3-bedroom villa surrounded by rice terraces in Ubud. Award-winning design with infinity pool overlooking the jungle valley.",
    images: ["🌿"],
    details: {
      bedrooms: 3,
      bathrooms: 3,
      landSize: "800 sqm",
      buildingSize: "350 sqm",
      yearBuilt: 2022,
      occupancyRate: "95%",
      managedBy: "Ubud Eco Resorts",
    },
    tokenAddress: "0x9abc...ijkl",
    network: "BNB Chain",
  },
  {
    id: "PROP-004",
    name: "Alam Sutera Residence",
    location: "Tangerang, Banten",
    type: "House",
    emoji: "🏡",
    totalValueUSD: 180000,
    tokenPriceUSD: 15,
    totalTokens: 12000,
    soldTokens: 2400,
    annualYield: 6.8,
    status: "Active",
    tags: ["Rental Income", "Tangerang"],
    description: "Modern 3-bedroom house in the prestigious Alam Sutera township. Gated community with 24/7 security, clubhouse, and easy toll access to Jakarta.",
    images: ["🏡"],
    details: {
      bedrooms: 3,
      bathrooms: 2,
      landSize: "150 sqm",
      buildingSize: "120 sqm",
      yearBuilt: 2020,
      occupancyRate: "85%",
      managedBy: "Alam Sutera Property Management",
    },
    tokenAddress: "0xdef0...mnop",
    network: "BNB Chain",
  },
  {
    id: "PROP-005",
    name: "Canggu Beach House",
    location: "Canggu, Bali",
    type: "Villa",
    emoji: "🌊",
    totalValueUSD: 620000,
    tokenPriceUSD: 40,
    totalTokens: 15500,
    soldTokens: 10850,
    annualYield: 11.3,
    status: "Active",
    tags: ["High Yield", "Bali"],
    description: "Trendy 5-bedroom beach house in Canggu's surf district. Walking distance to Echo Beach, surrounded by cafes and co-working spaces. High demand from digital nomads.",
    images: ["🌊"],
    details: {
      bedrooms: 5,
      bathrooms: 5,
      landSize: "700 sqm",
      buildingSize: "480 sqm",
      yearBuilt: 2023,
      occupancyRate: "90%",
      managedBy: "Canggu Stays",
    },
    tokenAddress: "0x1357...qrst",
    network: "BNB Chain",
  },
  {
    id: "PROP-006",
    name: "Menteng Heritage House",
    location: "Menteng, Jakarta",
    type: "House",
    emoji: "🏛️",
    totalValueUSD: 1200000,
    tokenPriceUSD: 100,
    totalTokens: 12000,
    soldTokens: 1200,
    annualYield: 5.9,
    status: "Active",
    tags: ["Capital Growth", "Jakarta"],
    description: "Rare colonial-era heritage house in Menteng, Jakarta's most prestigious neighborhood. Fully restored with modern amenities while preserving original architecture.",
    images: ["🏛️"],
    details: {
      bedrooms: 6,
      bathrooms: 5,
      landSize: "1200 sqm",
      buildingSize: "650 sqm",
      yearBuilt: 1935,
      occupancyRate: "80%",
      managedBy: "Heritage Properties Jakarta",
    },
    tokenAddress: "0x2468...uvwx",
    network: "BNB Chain",
  },
];

function formatUSD(amount) {
  if (amount >= 1000000) return `$${(amount / 1000000).toFixed(1)}M`;
  if (amount >= 1000) return `$${(amount / 1000).toFixed(0)}K`;
  return `$${amount}`;
}

function getFundedPct(p) {
  return Math.round((p.soldTokens / p.totalTokens) * 100);
}
